- name: Apache Setup Example
  hosts: all
  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create index.html file
      copy:
        dest: /var/www/html/index.html
        content: "Welcome to Apache!"

    - name: Add second line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Modification with lineinfile worked successfully."

    - name: Restart Apache service
      service:
        name: httpd
        state: restarted
